services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # disable buildx
      x-bake:
        use: false
    container_name: test-app
    ports:
      - "${HOST_PORT:-5000}:5000"
    environment:
      - APP_PORT=${APP_PORT:-5000}
